image:
  file: .gitpod.Dockerfile

# This will expose all necessary ports needed for your VNC image
ports:
  - port: 5000
    onOpen: open-preview

# This will make it so that on workspace start it will run a file called `app.py`
tasks:
  - command: python3 resnet-inference/imagenet-resnet50.py
